# fly.toml app configuration file generated for ff14-kotei-bot on 2026-06-01T10:12:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xivkoteibot'
primary_region = 'nrt'

[build]
  dockerfile = 'apps/bot/Dockerfile'

[deploy]
  release_command = 'pnpm --filter @ff14kotei/bot register-commands'

[env]
  DATABASE_URL = '/data/ff14kotei.db'
  HEALTH_PORT = '8080'
  NODE_ENV = 'production'

[[mounts]]
  source = 'ff14_kotei_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
